#!/bin/sh /etc/rc.common
START=95
STOP=10

start() {
    logger -t momo-rules "start update-momo-rules"
    if [ -x /usr/bin/update-momo-rules.sh ]; then
        /usr/bin/update-momo-rules.sh >/dev/null 2>&1 &
    fi
}

stop() {
    logger -t momo-rules "stop momo-rules"
}
